services:
  # A Docker web service
  - type: web
    name: Aliyundrive-Webdav
    env: docker
    repo: https://github.com/killgfat/aliyundrive-webdav-railway.git
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: REFRESH_TOKEN
        sync: false
      - key: WEBDAV_AUTH_USER
        sync: false
      - key: WEBDAV_AUTH_PASSWORD
        sync: false
